    - name: 1. Install
      yum:
       name: '{{ item }}'
       state: installed
      loop:
        - openvpn
        - easy-rsa
        - python-pip

    - name: 1.1 Install pip
      pip:
       name: pexpect

    - name: 1.2 Ensure dir
      file:
       name: /etc/openvpn/server
       state: directory

    - name: 2. Init.
      command:
        cmd: ./easyrsa init-pki
        chdir: /usr/share/easy-rsa/3

    - name: 3.Create CA
      expect:
        chdir: /usr/share/easy-rsa/3
        command: /usr/share/easy-rsa/3/easyrsa build-ca nopass
        responses:
          Easy-RSA CA: "lzj"

    - name: 4.Create server's private
      expect:
        chdir: /usr/share/easy-rsa/3
        command: /usr/share/easy-rsa/3/easyrsa gen-req openvpn nopass
        responses:
          Common Name: "lzj"

    - name: 5.Create server's cert
      expect:
        chdir: /usr/share/easy-rsa/3
        command: /usr/share/easy-rsa/3/easyrsa sign server openvpn
        responses:
          Confirm request details: "yes"

    - name: 6.Create DH
      command:
        cmd: /usr/share/easy-rsa/3/easyrsa gen-dh
        chdir: /usr/share/easy-rsa/3

    - name: 7.Collect
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        remote_src: yes
      loop:
        - {src: '/usr/share/easy-rsa/3/pki/ca.crt',dest: '/etc/openvpn/server/ca.crt'}
        - {src: '/usr/share/easy-rsa/3/pki/dh.pem',dest: '/etc/openvpn/server/dh.pem'}
        - {src: '/usr/share/easy-rsa/3/pki/issued/openvpn.crt',dest: '/etc/openvpn/server/openvpn.crt'}
        - {src: '/usr/share/easy-rsa/3/pki/private/openvpn.key',dest: '/etc/openvpn/server/openvpn.key'}

    - name: 8.Create conf
      copy:
        src: /usr/share/doc/openvpn-2.4.9/sample/sample-config-files/server.conf
        dest: /etc/openvpn/server.conf
        remote_src: yes

    - name: 9.Server.conf
      lineinfile:
        path: /etc/openvpn/server.conf
        regexp: '{{ item.old }}'
        line: '{{ item.new }}'
      loop:
        - {old: ';local a.b.c.d',new: 'local 10.0.1.81'}
        - {old: ';proto tcp',new: 'proto tcp'}
        - {old: 'proto udp',new: ';proto udp'}
        - {old: 'ca ca.crt',new: 'ca /etc/openvpn/server/ca.crt'}
        - {old: 'cert server.crt',new: 'cert /etc/openvpn/server/openvpn.crt'}
        - {old: 'key server.key',new: 'key /etc/openvpn/server/openvpn.key'}
        - {old: 'dh dh2048.pem',new: 'dh /etc/openvpn/server/dh.pem'}
        - {old: ';topology subnet',new: 'topology subnet'}
        - {old: ';push "route 192.168.10.0 255.255.255.0"',new: 'push "route 172.17.2.0 255.255.255.0"'}
        - {old: 'tls-auth ta.key 0',new: ';tls-auth ta.key 0'}
        - {old: ';log-append  openvpn.log',new: 'log-append  openvpn.log'}
        - {old: 'explicit-exit-notify 1',new: ';explicit-exit-notify 1'}

    - name: 10.Conf systemd
      copy:
        src: openvpn.service
        dest: /usr/lib/systemd/system/openvpn.service

    - name: 11.Systemd start
      systemd:
        name: openvpn.service
        daemon_reload: yes
        state: started
        enabled: yes
