'''
setvar1={"ABC","DEF","123","DEF","DEF"}
print(setvar1,type(setvar1))
#res=setvar1[0]
#print(res)
#setvar1[0]="hhh"
#print(setvar1)
setvar2=set()
print(setvar2,type(setvar2))
'''
dictvar={"up":1,"mid":2,"down":3}
print(dictvar,type(dictvar))
res=dictvar["mid"]
print(res,type(dictvar))
dictvar["mid"]=22
res=dictvar["mid"]
print(res,type(dictvar))