var2=3.14
var3=True
#var4=1+3j
var5="123"
#var6="abc13"
res=float(var2)
print(res,type(res))
res=float(var3)
print(res,type(res))
#res=float(var4)
#print(res,type(res))
res=float(var5)
print(res,type(res))
#res=float(var6)
#print(res,type(res))