var1=10
var2=3.14
var3=True
var4=1+3j
var5="123"
var6="abc13"
res=bool(var1)
print(res,type(res))
res=bool(var2)
print(res,type(res))
res=bool(var3)
print(res,type(res))
res=bool(var4)
print(res,type(res))
res=bool(var5)
print(res,type(res))
res=bool(var6)
print(res,type(res))
res=bool(0.0)
print(res,type(res))