var1=10
var2=3.14
var3=True
#var4=1+3j
var5="123"
var6="abc13"
res=complex(var1)
print(res,type(res))
res=complex(var2)
print(res,type(res))
res=complex(var3)
print(res,type(res))
#res=complex(var4)
#print(res,type(res))
res=complex(var5)
print(res,type(res))
res=complex(var6)
print(res,type(res))