    - name: 1. Install
      yum:
       name: '{{ item }}'
       state: installed
      loop:
        - git
        - python-pip
        - mysql-devel
        - gcc
        - automake
        - autoconf
        - python-devel
        - sshpass
        - lrzsz
        - readline-devel
        - mariadb

    - name: 1.2 Install PyMySql
      pip:
       name: '{{ item }}'
      loop:
       - PyMySql
       - pexpect

    - name: 1.3 Dir for pip speedup
      file:
        path: /root/.pip
        state: directory

    - name: 1.4 Copy pip conf
      copy:
        src: pip.conf
        dest: /root/.pip/pip.conf

    - name: 1.5 Install prepare
      command:
       cmd: '{{ item.comm }}'
       chdir: '{{ item.dir }}'
      loop:
        - { comm: 'git clone https://gitee.com/jumpserver/jumpserver.git', dir: '/opt' }
        - { comm: 'pip install -r requirements.txt', dir: '/opt/jumpserver/install' }

    - name: 1.6 Hot fix script
      script: comm.sh

    - import_task: db.yml

    - name: 2.Install jumpserver
      expect:
        command: /opt/jumpserver/install/python install.py
        responses:
               :
